name: Checkout Multiple Repos into Runner Workspace
on: workflow_dispatch

jobs:
  runner-workspace:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: /home/runner/work/learning-github

    steps:

      - name: Print GitHub workspace
        run: |
          echo "GITHUB_WORKSPACE is:  $GITHUB_WORKSPACE"

      - name: Checkout Self Repository
        uses: actions/checkout@v4
        with:
          path: webapp

      - name: Checkout Github Repository
        uses: actions/checkout@v4
        with:
          repository: 'chennaaws22/aws-terraform'
          ref: master
          path: aws-terraform
          token: ${{ secrets.GHREPO_TOKEN }}

      - name: List folders under working directory
        run: |
          echo "All Folders under $GITHUB_WORKSPACE:"
          ls -la $GITHUB_WORKSPACE

      - name: Show directory structure
        run: |
          echo "Self repository structure:"
          tree webapp || ls -R webapp

          echo "Other Github repository structure:"
          tree aws-terraform || ls -R aws-terraform
