name: Checkout Multiple Repos into Runner Workspace
on: workflow_dispatch

jobs:
  runner-workspace:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /home/runner/work/learning-github

    steps:
      - name: Create base directory
        run: mkdir -p /home/runner/work/learning-github

      - name: Checkout Self Repository
        uses: actions/checkout@v4
        with:
          path: /home/runner/work/learning-github/webapp

      - name: Checkout Github Repository
        uses: actions/checkout@v4
        with:
          repository: 'chennaaws22/aws-terraform'
          ref: master
          path: /home/runner/work/learning-github/aws-terraform
          token: ${{ secrets.GHREPO_TOKEN }}

      - name: List all folders and files in runner workspace
        run: |
          echo "Current working directory:"
          pwd
          
          echo "Top-level contents:"
          ls -l
          
          echo "Recursive listing of all files and folders:"
          find . -type f
          find . -type d

      - name: Show directory structure
        run: |
          echo "Self repository structure:"
          tree webapp || ls -R webapp

          echo "Other Github repository structure:"
          tree aws-terraform || ls -R aws-terraform
